stages:
  - test

linting:
  image: python:3.11-bullseye
  stage: test
  script:
    - pip install -r requirements.txt
    - isort .
    - black .
    - flake8 .
    - mypy .
  rules:
    - changes:
        - model/*
