[project]
authors = ["Elouen_Corvest <elouen.corvest@rwth-aachen.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "npqmodel-2016-master"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mdutils = ">=1.6.0,<2"
