[tool.ruff]
indent-width = 4
line-length = 88

[tool.ruff.lint]
fixable = ["ALL"]
ignore = [
  "ANN101",  # self-type annotation
  "ANN401",  # any
  "C901", # too complex
  "COM812",  # missing trailing comma
  "D", # all of documentation
  "E501",    # line-too-long
  "ERA001",  # commented-out code
  "FIX001",  # line contains FIXME
  "ISC001",  # single line implicit string concat
  "N806",    # non-lowercase variable
  "PGH003",  # specific rule type ignore
  "S110",    # try-except-pass
  "S301",    # pickle usage
  "TD001",   # invalid todo tag
  "TD002",   # missing todo author
  "TD003",   # missing todo link
  "PLR0912", # too many branches
  "PLR0913", # max num of arguments
  "PLR0915", # too many lines
  "PD010",   # pivot table
]
select = ["ALL"]
unfixable = []