PQ = remove_math(comps_table, r'$\mathrm{PQ}_\mathrm{ox}$')
PC_ox = remove_math(comps_table, r'$\mathrm{PC}_\mathrm{ox}$')
Fd_ox = remove_math(comps_table, r'$\mathrm{Fd}_\mathrm{ox}$')
ATP_st = remove_math(comps_table, r'$\mathrm{ATP}$')
NADPH_st = remove_math(comps_table, r'$\mathrm{NADPH}$')
H_lu = remove_math(comps_table, r'$\mathrm{H}^+$')
LHC = remove_math(comps_table, r'$\mathrm{LHC}$')
psbS = remove_math(comps_table, r'$\mathrm{Psbs}$')
Vx = remove_math(comps_table, r'$\mathrm{Vx}$')
PGA = remove_math(comps_table, r'$\mathrm{PGA}$')
BPGA = remove_math(comps_table, r'$\mathrm{BPGA}$')
GAP = remove_math(comps_table, r'$\mathrm{GAP}$')
DHAP = remove_math(comps_table, r'$\mathrm{DHAP}$')
FBP = remove_math(comps_table, r'$\mathrm{FBP}$')
F6P = remove_math(comps_table, r'$\mathrm{F6P}$')
G6P = remove_math(comps_table, r'$\mathrm{G6P}$')
G1P = remove_math(comps_table, r'$\mathrm{G1P}$')
SBP = remove_math(comps_table, r'$\mathrm{SBP}$')
S7P = remove_math(comps_table, r'$\mathrm{S7P}$')
E4P = remove_math(comps_table, r'$\mathrm{E4P}$')
X5P = remove_math(comps_table, r'$\mathrm{X5P}$')
R5P = remove_math(comps_table, r'$\mathrm{R5P}$')
RUBP = remove_math(comps_table, r'$\mathrm{RUBP}$')
RU5P = remove_math(comps_table, r'$\mathrm{RU5P}$')
MDA = remove_math(comps_table, r'$\mathrm{MDA}$')
H2O2 = remove_math(comps_table, r'$\mathrm{H_2O_2}$')
DHA = remove_math(comps_table, r'$\mathrm{DHA}$')
GSSG = remove_math(comps_table, r'$\mathrm{GSSG}$')
Trx_ox = remove_math(comps_table, r'$\mathrm{Trx_{ox}}$')
E_CBB_inactive = remove_math(comps_table, r'$\mathrm{E}_\mathrm{inactive}$')

{ode(PQ)} &= \\
{ode(PC_ox)} &= \\
{ode(Fd_ox)} &= \\
{ode(ATP_st)} &= \\
{ode(NADPH_st)} &= \\
{ode(H_lu)} &= \\
{ode(LHC)} &= \\
{ode(psbS)} &= \\
{ode(Vx)} &= \\
{ode(PGA)} &= \\
{ode(BPGA)} &= \\
{ode(GAP)} &= \\
{ode(DHAP)} &= \\
{ode(FBP)} &= \\
{ode(F6P)} &= \\
{ode(G6P)} &= \\
{ode(G1P)} &= \\
{ode(SBP)} &= \\
{ode(S7P)} &= \\
{ode(E4P)} &= \\
{ode(X5P)} &= \\
{ode(R5P)} &= \\
{ode(RUBP)} &= \\
{ode(RU5P)} &= \\
{ode(MDA)} &= \\
{ode(H2O2)} &= \\
{ode(DHA)} &= \\
{ode(GSSG)} &= \\
{ode(Trx_ox)} &= \\
{ode(E_CBB_inactive)} &= \\
