[project]
authors = ["Elouen_Corvest <elouen.corvest@rwth-aachen.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "modelbase1"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
modelbase = ">=1.57.6,<2"

[pypi-dependencies]
mdutils = ">=1.6.0, <2"
glossary-utils = { path = "../../../Templates/utils/", editable = true }
ipykernel = ">=6.29.5, <7"
setuptools = ">=75.8.0, <76"
